/* Конфиг админки. Зашифрованный токен сюда вставляется один раз
   владельцем после запуска admin/encrypt-token.html.
   Файл публичный — в нём не должно быть PAT в открытом виде. */
window.ADMIN_CONFIG = {
  owner: 'Lab301-ru',
  repo: 'inari',
  branch: 'main',
  // Вставить сюда результат encrypt-token.html (base64-строка):
  encryptedToken: 'eyJ2IjoxLCJzYWx0IjpbMTY3LDIwLDIxOCw2MSwyMDIsMTAyLDI0OSwyMDcsNywxMzcsMjQ4LDk4LDcsMTgwLDExNSwxNzFdLCJpdiI6WzIwNSwxNzQsNjEsMTUsNzUsOTEsMTQ1LDU0LDExNywxOTYsMTA2LDMyXSwiZGF0YSI6WzksNjQsMiwxODUsNzMsMTM2LDE1NSwzMiw2Myw1MSw0NSw0MCwxMzQsMjIsMjM5LDcsMjIzLDIzNiwyMjMsODksOTUsMCwxNjQsMzksNCw0MSwyMzMsMjE1LDEyMyw0OSwxOCwxODYsMTc2LDU4LDIzMSwxODIsMjIyLDQsODUsMjIyLDE1OSwxLDE3Miw5NSwyMTcsMTY5LDE4LDE1OSwxMSwxMTgsNTUsMjM2LDEyMCwxMDIsMjAxLDE5NSwyMDcsNzIsMjQzLDIwNywyNDYsNzksMjI3LDEwNCwxNjcsMTA5LDE5NSwxNzksMTgyLDE0NiwyNDQsMjM2LDIzOCw2MywyNDMsMjAyLDE5MywyMTIsNzUsMTAyLDQ5LDEwLDExNywxMDMsMTgyLDU1LDEzMCwxNCwyMzgsMTY0LDM3LDI1NCwxLDExMSw1LDE0OCwxNzAsMTU5LDgyLDE1OSw1MiwzNywzLDE1OCwxNzUsMTgxLDc4LDIxMSwyNDVdfQ=='
};
